### PR TITLE
Update the library and example notebooks to be compatible with the latest version of fastai

### LINKED ISSUE #17: Error when importing the library with the latest version of fastai
This error occurs when use `import faststyle`

```
/opt/conda/envs/fastai/lib/python3.8/site-packages/faststyle/__init__.py in <module>
      2 
      3 from .core import *
----> 4 from .data import *
      5 from .layer_features import *
      6 from .models import *

/opt/conda/envs/fastai/lib/python3.8/site-packages/faststyle/data.py in <module>
     58 
     59 # Cell
---> 60 class ImageWeight(Tuple):
     61   @classmethod
     62   def create(cls, fnw, imcls=PILImageX): return cls(imcls.create(fnw[0]), Weights(fnw[1]))

NameError: name 'Tuple' is not defined
```

### PR DESCRIPTION
**Pull request by ncduy0303**
I updated the library and example notebooks to be compatible with the latest version of fastai: `fastai: 2.0.16`, `fastcore: 1.2.5`. This should fix the issue raised in #17.

### CODE REVIEW

**Comment by ncduy0303** [comment]
Set requirements for `torch==1.6.0` and `torchvision==0.7` becuase of the issue mention [here](https://github.com/fastai/fastai/issues/2768)

**Comment by lgvaz** [comment]
That's really really awesome @ncduy0303!!! Thanks **a lot** for this =)

It makes me very happy to know that the library is still working!!

**Comment by ncduy0303** [comment]
You're welcome =)
Perhaps you can make a new release on pypi?

**Comment by lgvaz** [comment]
Will do!

**Comment by lgvaz** [comment]
Alright, just uploaded version `0.0.4` to pypi, can you confirm it's working for you?

**Comment by ncduy0303** [comment]
Yup, it's working. Thanks a lot!

**Pull request merged**
